### ISSUE TITLE
Unable to download the phar

### ISSUE THREAD

**Issue by ramakrishnab** [steadweb/nyx#31]
wget https://steadweb.github.io/nyx/nyx.phar resulting in 404.

Resolving steadweb.github.io... 151.101.60.133
Connecting to steadweb.github.io|151.101.60.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-26 20:15:41 ERROR 404: Not Found.

**Comment by steadweb** [comment]
Thanks @ramakrishnab - duplicate of https://github.com/steadweb/nyx/issues/14

**Comment by steadweb** [comment]
Fixed.
